services:
  # Serviço para o banco de dados PostgreSQL
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - airflow-network

  # Serviço para o Apache Airflow
  airflow:
    image: apache/airflow:2.7.0
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__S3__S3_ENDPOINT_URL=http://minio:9000
      - AIRFLOW__S3__AWS_ACCESS_KEY_ID=minio
      - AIRFLOW__S3__AWS_SECRET_ACCESS_KEY=minio123
      - AIRFLOW__S3__AWS_REGION=us-east-1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["bash", "-c", "airflow db init && exec airflow webserver & exec airflow scheduler"]
    networks:
      - airflow-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000"]
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 10s

  # Serviço para o MinIO
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always
    networks:
      - airflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 10s

networks:
  airflow-network:

volumes:
  postgres_data:
  minio_data: